version: '2'

services:
#    nginx:
#        extends:
#            file: docker-common.yml
#            service: nginx
#        ports:
#            - 8000:8000
#        volumes:
#            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        volumes_from:
#            - backend
#    postgres:
#        extends:
#            file: docker-common.yml
#            service: postgres
#        ports:
#            - 5433:5432
#        volumes:
#            - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    mongo:
        image: mongo
        ports:
          - "27017:27017"
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=MyR4bb1t!p@a5s
        ports:
          - "5672:5672"
          - "15672:15672"  # here, we can access rabbitmq management plugin
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
        links:
            - mongo
        entrypoint:
            - /django-entrypoint.sh
        ports:
            - "8000:8000"
    worker:
        build:
          context: .
          dockerfile: ./docker/celery_worker/Dockerfile
        entrypoint:
          - /worker-entrypoint.sh
        volumes:
          - .:/django
        links:
          - rabbit
        depends_on:
          - rabbit

#    frontend:
#        extends:
#            file: docker-common.yml
#            service: web
#        links:
#            - backend
#        entrypoint:
#            - /web-entrypoint.sh
